# Generated by Django 4.2.10 on 2024-02-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tour",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
