# Generated by Django 4.2.10 on 2024-02-23 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tours", "0003_tourcategory_remove_tour_is_featured_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tourcategory",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
    ]
